socketcan_interface_node:
  ros__parameters:
    if_name : "can0"

teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.5

    enable_button: 4

joy_node:
  ros__parameters:
    deadzone: 0.1

base_driver_node:
  ros__parameters:
    wheel_radius: 0.02
    attached_direction: 0.15
    device_canid: 5


joy_commander_node:
  ros__parameters:
    mode_button: 5
    threshold: 20

